### PR TITLE
Fix recent expl3 error

### LINKED ISSUE #2: Broken with new expl3
(This is as of October 21, 2016.)

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
/usr/local/texlive/2016/texmf-dist/tex/latex/withargs/withargs.sty:155: LaTeX e
rror: "kernel/non-base-function"
! 
! Function '\__withargs_var:nx' is not a base function
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
```

### PR DESCRIPTION
**Pull request by pthariensflame**
Fixes mhelvens/latex-withargs#2.

This is the most straightforward fix I could find; I contemplated using `\cs_new:Npn`, but I didn't want to have to alter the code *too* significantly.  This way, the change is near-trivial, and it still expresses the correct intent.

### CODE REVIEW

**Comment by mhelvens** [comment]
Awesome, thanks! I'll double check this weekend and merge.

**Comment by pthariensflame** [comment]
@mhelvens Any news?

**Comment by mhelvens** [comment]
Double checked and merged. Thanks for your contribution! Will publish the new version to CTAN shortly.

**Comment by pthariensflame** [comment]
Thank you!  This means some of my projects will build again.

**Pull request merged**
